"""exec 02 aula 04

Revision ID: fdb415e5b50b
Revises: 2e389b6f6105
Create Date: 2026-05-31 19:26:01.224471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdb415e5b50b'
down_revision: Union[str, Sequence[str], None] = '2e389b6f6105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # add colummun
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # mokoza valores onde não tem
    op.execute("UPDATE users SET updated_at = CURRENT_TIMESTAMP")
    # 
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column(
            'updated_at',
            existing_type=sa.DateTime(),
            server_default=sa.text('CURRENT_TIMESTAMP'),
            nullable=False,
        )
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###
